#!/usr/bin/env bash

shopt -s nullglob
set -ueo pipefail

info() {
    printf "%s\n" "$*" >&2
}
warning() {
    printf "\e[33m%s\e[m\n" "$*" >&2
}
error() {
    printf "\e[31m%s\e[m\n" "$*" >&2
}

open() {
    code "$1"
    exit
}

current="$(pwd)"
workspace=""
multiroot=""

while true; do
    workspace_files=("$current/"*".code-workspace")
    if [ "${#workspace_files[@]}" -eq 1 ]; then
        workspace="${workspace_files[0]}"
        multiroot="yes"
        break
    fi
    if [ "${#workspace_files[@]}" -gt 1 ]; then
        error "multiple workspace files found in '$current'"
        exit 1
    fi
    if [ -f "$current/.vscode/settings.json" ]; then
        workspace="$current"
        break
    fi
    parent="$(dirname "$current")"
    if [ "$parent" = "$current" ]; then
        break
    fi
    current="$parent"
done

if [ -n "$workspace" ]; then
    if [ -n "$multiroot" ]; then
        info "multi-root workspace: $workspace"
    else
        info "single-root workspace: $workspace"
    fi
    open "$workspace"
fi

gitroot="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$gitroot" ]; then
    info "git root: $gitroot"
    open "$gitroot"
fi

warning "warning: cannot find workspace root"
open .
