#!/usr/bin/env bash

shopt -s nullglob
set -ueo pipefail

info() {
    printf "%s\n" "$*" >&2
}
warning() {
    printf "\e[33m%s\e[m\n" "$*" >&2
}
error() {
    printf "\e[31m%s\e[m\n" "$*" >&2
}

open() {
    code "$1"
    exit
}

current="$(pwd)"
ws_file=""

while true; do
    ws_files=("$current/"*".code-workspace")
    if [ "${#ws_files[@]}" -eq 1 ]; then
        ws_file="${ws_files[0]}"
        break
    fi
    if [ "${#ws_files[@]}" -gt 1 ]; then
        error "multiple workspace files found in '$current'"
        exit 1
    fi
    parent="$(dirname "$current")"
    if [ "$parent" = "$current" ]; then
        break
    fi
    current="$parent"
done

if [ -n "$ws_file" ]; then
    info "multi-root workspace: $ws_file"
    open "$ws_file"
fi

gitroot="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$gitroot" ]; then
    info "git root: $gitroot"
    open "$gitroot"
fi

warning "warning: cannot find workspace root"
open .
